name: Deploy App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull image from GHCR
        run: docker pull ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest

      - name: Deploy to remote server
        run: |
          ssh user@your-remote-server 'docker stop your-container && docker rm your-container'
          ssh user@your-remote-server 'docker run -d --name your-container -p 80:80 ghcr.io/your-username/your-image:latest'
