name: Publish container

on:
  push:
    branches:
      - dev

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/${{ github.repository }}

jobs:
  update-container:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Info
        run: |
          echo imagename1 $IMAGE_NAME
          echo imagename1 ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest
          echo github.repository_owner ${{ github.repository_owner }}
          echo github.repository ${{ github.repository }}
          echo IMAGE_NAME:latest $IMAGE_NAME:latest

      - name: Build and push container
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.sha }}
