name: Deploy App

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest
  SSH: ${{vars.SSH_USER}}@${{vars.SSH_HOST}}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add SSH key to known hosts
        run: |
          ssh-keyscan -H ${{ vars.SSH_HOST }} >> ~/.ssh/known_hosts


      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull image from GHCR
        run: docker pull $IMAGE_NAME

      - name: Deploy to remote server
        run: |
          echo "Deploying to $SSH"
          echo "Checking running containers..."
          echo 'docker ps -a'
          ssh $SSH 'docker stop ${{vars.APP_NAME}} && docker rm ${{vars.APP_NAME}}  || true'
          echo "Starting container..."
          # ssh $SSH 'cd ${{vars.WORK_DIR}} && docker run -d --name ${{vars.APP_NAME}} -p 3000:3000 $IMAGE_NAME'
          ssh $SSH 'set -x; cd ${{vars.WORK_DIR}} && docker run -d --name ${{vars.APP_NAME}} -p 3000:3000 $IMAGE_NAME'
          echo "Container started"
