name: Deploy App

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest
  SERVER: ${{vars.SSH_USER}}@${{vars.SSH_HOST}}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull image from GHCR
        run: docker pull $IMAGE_NAME

      - name: Deploy to remote server
        run: |
          ssh $SERVER 'docker stop ${{vars.APP_NAME}} && docker rm ${{vars.APP_NAME}}'
          ssh $SERVER 'cd ${{vars.WORK_DIR}} &&  docker run -d --name ${{vars.APP_NAME}} -p 80:80 $IMAGE_NAME'
