name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to GitHub Container Registry
      run: echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build and push Docker image
      run: |
        docker build -t ghcr.io/${{ github.repository }}/my-node-app:latest .
        docker push ghcr.io/${{ github.repository }}/my-node-app:latest

    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        envs:
          DOCKER_IMAGE: ghcr.io/${{ github.repository }}/my-node-app:latest
        script: |
          docker pull $DOCKER_IMAGE
          docker stop my-node-app || true
          docker rm my-node-app || true
          docker run -d --name my-node-app -p 3000:3000 $DOCKER_IMAGE
